### ISSUE TITLE
Extreme FPS drops when holding right click when building

### ISSUE THREAD

**Issue by jonalange** [dexman545/Fabric-Autoswitch#51] opened 2022-11-13 17:21 UTC
_First of all: I rebound (swapped) left and right click. So for me this problem actually occurs when I hold left click (placing block, eating food etc.) but I will talk about right click because that's the common keybind everybody else uses._

For some reason after some time (longer sessions without restarting the game) it happens that I have extreme FPS drops (down to 2 FPS) when I try to build and hold rightclick to place multiple blocks. Also happens when eating. 
When I then hit the keybind for auto switch to toggle everything goes back to normal (when auto switch is deactivated). When activated again the problems happens again.

It feels like that the mod is looking for updates so often that it causes the whole game to lag.

Hardware isn't an option here. I run a Ryzen 9 5900X with RTX 3080 Ti and 12 GB allocated to minecraft.

I have some other mods installed, but it's still pretty lightweight (in terms of big modpacks).

If you need any logs from me let me know.

**Comment by dexman545** [comment] 2022-11-13 21:32
Please provide a log file, and if possible a spark profile when the lag occurs.

**Comment by dexman545** [comment] 2022-11-14 01:48
Does the same also happen when attacking?

**Comment by jonalange** [comment] 2022-11-14 15:21
@dexman545 
What exact logs and spark profile do you need? Never used spark and will do my best to give you what you need. 
I look into it when I'm at home later. But no, it doesn't happen when attacking. 
At least that's what I think, because I don't hold the attack button with the sword. But while digging it's no problem.

**Comment by dexman545** [comment] 2022-11-14 16:24
I need the standard MC log file. I received a similar report for attacking with AS via curseforge, and their log showed a lot of log spam - that isn't from AS, so likely a mod conflict between AS and some mod.

For Spark, just a normal spark profile. It should automatically upload the profile, so I just need the link to that.
In game, once you can reproduce the lag, run `/sparkc profiler start`, reproduce the lag for a bit, then run `/sparkc profiler stop`.

**Comment by jonalange** [comment] 2022-11-20 12:12
@dexman545 Sorry for the late reply. Didn't play that much the last few days and when I did I didn't had the problem as much.

Today I had this problem again, but not as extreme. It dropped from 60-70 FPS (with shader) down to 20-30 FPS
Not as bad as it used to be. But my sessions just isn't long enough right now

https://spark.lucko.me/l8hxYcxbd7
[latest.log](https://github.com/dexman545/Fabric-Autoswitch/files/10049613/latest.log)

**Comment by dexman545** [comment] 2022-11-21 00:26
Thanks for the profile.

Good news: I think I see where the issue is coming from.
Bad news: I'm making a shot in the dark at fixing it.

Here is an alpha version that may fix the issue. Please let me know if it does or does not.
https://github.com/dexman545/Fabric-Autoswitch/releases/tag/test

**Comment by dexman545** [comment] 2023-01-03 00:19
Closing as this seems to be fixed.

**Closed by dexman545** 2023-01-03 00:19 UTC
